= Phase 01 BIM Execution Plan
Jon Szczesniak <jszczesniak@bcj.com>
1.0, July 29 2014, First draft of BxP
:client: CLIENT
:project_name: PHASE 01
:bcj_project_number: 16xxx
:toc:
:icons: font

{client} +
{project_name} +
BUILDING INFORMATION MODELING EXECUTION PLAN +
{bcj_project_number}

JANUARY 2016

== Introduction
=== Overview
This BIM Execution Plan [BxP] provides a baseline document that helps guide the project team through the process of setting and achieving projects goals with regards to Building Information Modeling.

The intent of the BxP is to clearly define roles and responsibilities of project members, facilitate clear communication, set project goals, and clarify the expectations and processes for BIM deliverables through the various stages of a project.

It is essential that all parties follow the standards and procedures set forth in the BxP.

Communication is key to a successful BIM project. This BxP and kick-off meeting serve to begin the project with strong and clear communication. The project team will continue a minimum of bi-weekly BIM meetings to ensure that all parties are following the BxP.

Before the creation and exchange of any models the BxP will be reviewed with the entire project team during the project kick-off meeting at the start of the project. This meeting will be coordinated by BCJ. Each discipline should ensure that at least one model manager, or otherwise knowledgeable person, is in attendance.

Consultant’s responsibilities under the Terms and Conditions of Agreement between Architect and Consultant shall apply to the development of BIM Model(s). All consultants are responsible for the development and implementation of BIM content within the respective disciplines and as required by this document.

The BxP is a living document and will be maintained through the life of the project. It should be updated and sent to the project team after each bi-weekly BIM meetings.

[glossary]
=== Definition of Terms
[glossary]
As-Built Model::
Model(s) based on Construction Model(s) and installed conditions.

Construction Model::
Models(s) based on criteria that are important to the translation of the facility’s construction.

Design Intent Model::
Model(s) based on criteria that are important to the translation of the facility’s design.

Design Intent Record Model::
Model(s) based on Design Intent Model(s) and all design and contract revisions upon substantial completion.

Facility Attribute Data::
Associated intelligent attribute data (e.g. manufacturer, model, warranty information, etc.)

Level of Development (LOD)::
Level of completeness to which a model element is developed at the end of each design and construction phase.

Model Element Author (MEA)::
Responsible party for developing the BIM content of a specific Model Element to the LOD required for a particular phase of the Project.

Model Element::
Portion of the model(s) representing a component, system, or assembly within a building or site.

=== Right of Reliance
The Building Information Model produced by the project stakeholders associated with the Design Team will serve as the basis of design and is considered a Design Intent Model only.  The model prepared by the Design Team will be used by Contractor to prepare a Construction Model.  This Right of Reliance pertains to all models and applications associated with the model and associated applications.

The Construction Team may rely on the accuracy of the model(s) prepared by the Design Team in accordance with traditional Standard of Care provisions that apply and govern the design and construction of comparable buildings in two (2) - dimensional design formats and methods.

Conversely, the Design Team may rely on the accuracy of the model(s) prepared by the Construction Team in accordance with traditional Standard of Care provisions that apply and govern the preparation of shop drawings, fabrication drawings, sequencing and other instruments used to convey the means and methods under the control of Contractor, its subcontractors, consultants and other agents working on this project.

As mutually agreed by all parties including BCJ, Contractor and Client, nothing shall be construed by the content and/or preparation of the associated model(s) as a warranty or guarantee of accuracy and/or completeness by the Design Team.  Standard and traditional procedures for design, documentation, means and methods, shop drawing submittals, verification by the contractor, requests for information in question, etc. shall apply to the design, construction and construction administration of the project.

The construction manager, contractors and subcontractors shall be solely responsible for means and methods and the execution of the Design Intent Model through the execution, preparation and management of delegated design, the Construction Model(s), fabrication, installation and construction.

=== References
This BxP was written using many references these and others are listed below.

BIM Execution Planning Guide developed by CIC Research Group, The Pennsylvania State University. http://bim.psu.edu/
	BIM Project Execution Guide v2.1
	BIM Goal Use Analysis Worksheet
	Information Exchange Worksheet

AIA Document G202–2013, Project Building Information Modeling Protocol Form
 

== Project Data
=== General Info
Phase 1
Project # 15XXX
Client
Address
1020 Some Street
City, State 15222
[UPDATE THE ADDRESS – BUILDING 37?]
Client Project Number
YY-00-000

=== Description
Project Description
[CONFIRM AND UPDATE GSF and PARKING]

=== Project Schedule / Phases / Milestone
[Substitute for an item in the Appendix for the full project schedule, including Info Exchanges]

Project Phase	Estimate Start Date	Estimated Completion Date
Schematic Design	TBD	TBD
Design Development	TBD	TBD
Construction Documents	TBD	TBD


== Team Contacts
=== Project Design Team
The contacts provided below are those to be used as the day-to-day contacts and/or Project Managers for each discipline. If there is more than on PM or contact, provide their information and note any specific areas of control for clarity, see the Architecture group below as an example.
Architecture
Bohlin Cywinski Jackson, Project Manager
Rob Aumer | raumer@bcj.com | 412.765.3890

Bohlin Cywinski Jackson, Site
First Lastname | flastname@bcj.com | 000.000.0000
Structure, Mechanical, Electrical, Plumbing, Lighting, Acoustics, Code
MEP Company
First Lastname | flastname@bcj.com | 000.000.0000
Civil
STV
First Lastname | flastname@bcj.com | 000.000.0000
Fire Protection
FP Company
First Lastname | flastname@bcj.com | 000.000.0000
Landscape
First Lastname | flastname@bcj.com | 000.000.0000
Information Communication Technology
ICT Company
First Lastname | flastname@bcj.com | 000.000.0000
Audio Visual
Audio Visual Company
First Lastname | flastname@bcj.com | 000.000.0000
Envelope
Envelope Company
First Lastname | flastname@bcj.com | 000.000.0000
Parking Structure Architect
Envelope Company
First Lastname | flastname@bcj.com | 000.000.0000

=== BIM + CAD Leads
The contacts provided below are those actively managing the models and, in the case where the discipline does not use BIM, CAD documentation files for each discipline. This is to ensure we connect the right people and encourage communication. If there is more than one model manager provide their information and note any specific areas of control for clarity, see the Architecture group below as an example.
Architecture
Bohlin Cywinski Jackson, BIM Manager
First Lastname | flastname@bcj.com | 000.000.0000
Structure
First Lastname | flastname@bcj.com | 000.000.0000
MEP
First Lastname | flastname@bcj.com | 000.000.0000
Civil
STV
First Lastname | flastname@bcj.com | 000.000.0000
Fire Protection
FP Company
First Lastname | flastname@bcj.com | 000.000.0000
Landscape
First Lastname | flastname@bcj.com | 000.000.0000
Information Communication Technology
ICT Company
First Lastname | flastname@bcj.com | 000.000.0000
Audio Visual
Audio Visual Company
First Lastname | flastname@bcj.com | 000.000.0000
Envelope
Envelope Company
First Lastname | flastname@bcj.com | 000.000.0000
Parking Structure Architect
Parking Structure Company
First Lastname | flastname@bcj.com | 000.000.0000


== Technology
=== Software
The project will be documented using Autodesk Revit. Below is a list of the disciplines on the project team and what software they will be using.

Architecture	Revit
Parking Structure Architect	Revit
Civil	[Civil 3D]
Landscape	[AutoCAD]
Structure 	Revit
Mechanical	Revit
Electrical	Revit
Plumbing	Revit
Fire Protection	Revit
Information Communication Technology	[???]
Audio Visual	[???]
Envelope	[???]
Lighting	[???]
Acoustics	[???]
Version & Updating
All disciplines will start with the most current version of their respective software. For Autodesk software (AutoCAD, Civil3D, Revit, Navisworks, etc) the current version of which is 2016.

As Autodesk generally updates their software in June of each year, all updates to the software will be coordinated by BCJ. All Service Releases will be installed as they come out. The project team will switch to the newest version of Revit within 1 month of the release of the Service Release of that version (e.g. Revit 2015 SR 1). Upgrades should be coordinated with a project’s schedule and ideally would occur directly after a major milestone. These version updates and service releases will be coordinated with each consultant’s BIM lead and project manager in advance of the team adoption to minimize any impact to the overall project schedule.
Plugins
List any Plugins or Add-ons to your software that may be used to supplement your workflow. If applicable note what function the plugin will perform.
Bohlin Cywinski Jackson
Worksharing Monitor for Autodesk Revit	Interoffice monitoring of central file access
Dynamo for Revit			Data manipulation and workflow optimization
COBie extension			Data extraction to COBie formatted workbooks
Ideate BIMlink			Data extraction and linking to Excel
BCFier				Creation, Editing and Management of BCF files for team coordination

=== Hardware
Each company is required to provide their team with hardware that meets the system requirements as defined by Autodesk. Links are provided to Autodesk’s webpage below.

Revit hardware must meet the Performance configuration listed here:
System requirements for Autodesk Revit 2015
System requirements for Autodesk Revit 2016
It is recommended that Mac users access Revit via Bootcamp

AutoCAD hardware must meet the highest configuration recommended
System requirements for Autodesk AutoCAD 2015


== Collaboration
=== Strategy
The project will be developed in distinct volumes:
Volume 01 – Site
Volume 02 – Parking Structure & CUP
Volume 03 – Plinth
Volume 04 – Tower 01 - North
Volume 05 – Tower 02 - Sourth

Each volume of the project will be developed by unique teams made up of the same set of consultants. BCJ will have oversight on all volumes of the project acting as the Design Architect, but only intends to lead as the Architect of Record for the Plinth and two Towers. A master plan document will be used at the end of schematic design to coordinate the respective volumes.

Since each volume will be developed along its own schedule, it is recommended that each unique project team clearly define the specific dates of meetings and information exchanges. The following section should be used as a guideline to assist in planning this schedule.
05.2	Meetings
The following table lists team meetings. These meetings are specific to the project’s BIM uses and goals.

Meeting Type	Stage	Frequency	Participants	Location
BIM Kick-Off	Project Start	One-Time	Design Team + UA + GC/CM
TBD

BIM Execution Review	SD-CD	Bi-Monthly
Design Team
TBD

Design Coordination	SD-CD	Weekly	Design Team 	TBD
Construction Progress
Additional BIM Meetings

All appropriate Client Facilities Management & Operations personnel and partners will be included in BIM kick-off meeting, as well as all major milestone conflict meetings (as outlined in the Quality Control Schedule below). Attendance at additional conflict meeting and Design Coordination meetings is at the discretion of Client personnel and their model managers.

=== Information Exchange
The team will be exchanging information on a staggered bi-weekly basis. The Architecture model(s) will be provided one week and the remaining disciplines’ models/files will be exchanged the following week.

Additionally, each discipline will exchange a working .pdf set of drawings with their model. There are instances where elements of the project will not be modeled, but will be documented in two-dimensions only. By publishing a progress .pdf set of drawings with the model, we are ensuring that other members of the design team have the information necessary to fully coordinate the two scopes of work. The .pdf should at the minimum be the plans of the project, but may also include any other portions of the project that have been modified or progressed since the previous version of model was issued.

All files will be uploaded to Dropbox by 5:00pm EST each Friday
Dropbox Information
Address:
User:
Pass:
[UPDATE THIS INFORMATION WHEN WE ESTABLISH THIS DROPBOX FOLDER]

Each discipline will have its own folder to upload models. All models and files should be exchanged via Dropbox transferring files by email attachment should be avoided.

Prior to uploading a Revit file to the project FTP site, verify that your worksets have been managed according to section Error! Reference source not found.. Additionally, Audit the model, and Detach from Central so that there are no dependency issues when posting to the FTP site. Finally, Purge the unused families to reduce the overall file size.


Information Exchange	Sender	Receiver	Freq.	Date	File Type
Design Authoring & 3D Coordination	A	S,M,E,P,C,LA	Bi-Weekly	[MM-DD-YY]	.rvt
.dwg
.pdf
	S,M,E,P	A	Bi-Weekly	[MM-DD-YY]	.rvt
.pdf
	C,LA		Bi-Weekly	[MM-DD-YY]	.dwg
.pdf

=== Collaboration/Communication Platform
Internally, the BCJ team will be using Slack with integrated Screen Hero for communication and screen sharing for day-to-day communication.

Externally, BCJ will be the owners of a Bluebeam Studio session to be used for redline mark-up and sharing between disciplines as well as between portions of the project. For additional information on Bluebeam, see this link.
Bluebeam Studio Information
Session Use
Session ID:
Session URL:
[UPDATE THIS INFORMATION WHEN WE ESTABLISH A BLUEBEAM STUDIO SESSION]

For modeling collaboration, there will likely be a multitude of software used. The options should be discussed within each unique project as selected based on that team’s knowledge base. For larger coordination efforts (by level, or at major milestones) teams should be using Navisworks to check for hard and soft collisions between trades. For smaller coordination efforts (specific design instances or tracking issues in meetings) BCFier should be used and transferred between consultants.

Additionally, unique teams to the project may opt to use other software to track modeling collision efforts such as Solibri, Tekla, A360 or other.


== Model Use
=== BIM Goals
The Building Information Modeling will be used on this project for the following goals. All models should be developed in a way that ensures these goals are achieved.  The BIM model(s) being developed by the design teams will be developed with the highlighted goals in mind.  The BIM model will also be developed to allow the construction manager team and campus operations team to reference the design BIM model as a guide and to develop their own internal BIM models.
[Use Appendix A – BIM Use Analysis Worksheet to determine appropriate uses of the model]

Planning	Design	Construction	Operation
Programming	Design Authoring	Site Utilization Planning	Building Maintenance
Site Analysis	Design Review	Construction Systems	System Analysis
	3D Coordination	3D Coordination	Asset Management
	Structural Analysis	Digital Fabrication	Space Management
	Lighting Analysis	3D Control & Planning	Disaster Planning
	Energy Analysis	Record Modeling	Record Modeling
	Mechanical Analysis
	Other Eng. Analysis
	Sustainability Analysis
	Code Evaluation

Phase Planning (4D)	Phase Planning (4D)	Phase Planning (4D)	Phase Planning (4D)
Cost Estimation	Cost Estimation	Cost Estimation	Cost Estimation
Existing Conditions	Existing Conditions	Existing Conditions	Existing Conditions


== Project Standards
=== Discipline Designators
The following is a subset of the full Discipline Designator table listed in section Sheet Naming. The items noted in this section are to be used as prefixes for both file naming as described below, as well as for correspondence and archiving of the project.

Designator	Discipline
V	Survey/Mapping
B	Geotechnical
C	Civil
LA	Landscape
S	Structural
A	Architectural
I	Interiors
F	Fire Protection
P	Plumbing
M	Mechanical
E	Electrical
W	Distributed Energy
T	Telecommunications
LI	Lighting
AC	Acoustics
IT	Information Communication Technology
AV	Audio / Visual
EV	Envelope

=== Volume Designators
The following acronyms will be used to identify the various volumes of the building in accordance with section 05.1 Strategy.

Designator	Volume
MP	Master Plan
SE	Site
PK	Parking
CP	C.U.P.
PL	Plinth
TN	Tower 01 – North
TS	Tower 02 – South

=== File Naming
Revit models, and CAD files, will follow the naming convention:

Volume Designator-Discipline Designator - Description (if applicable)

For example PL-A – Shell.rvt would indicate the Architectural Shell model for the Plinth volume. The description designator is only necessary where there are multiple models from a trade, ie; Shell and Core, Interiors, Furniture, etc.

// [DISCUSS THE NEED FOR ADDING A DATE WITH THE TEAM]

=== File Setup
The project location, level, and initial structural grid will be established by BCJ for the initial model exchange.

The project survey point will be identical for all Volumes of the Project. It is located at [Description][indicated with a red dot in the image below].
The coordinates of the survey point are as follows:
N: XXX’
E: XXX’
EL: XXX.XX’

Project base point will be located at intersection of grid A/1 [location of monument or existing structure with an established survey point indicated on current survey] [secondary geodesic survey marker or property line coordinate indicated on current survey][indicated with a blue dot in the image below]. The PBP may be unique for each Volume of the project. If unique points are uses, they must be explicitly noted in this section.

All files will be linked by shared coordinates. Once linked, each model should “Acquire Shared Coordinates” from the Architectural model distributed during the initial model exchange.

=== Worksets
Default Worksets
The following Worksets will be standard for each model:

+Coordination
Shared Levels & Grids
X-R-Site

The +Coordination workset contains model elements that are contained in more than one model for the expressed purpose of coordination between disciplines. In particular, model elements that will change Model Element Author during the design process as indicated in the Model Development Matrix are likely to be included on this workset (i.e. light fixtures, plumbing fixtures, floor drains, structural walls\floors, et cetera).

Shared Levels & Grids will contain the levels and grids. Consultants should copy-monitor the levels and grids from the XX_A model, where XX is the volume designator as noted above. The Architectural model is the only model that contains non-Copy/Monitored grids and levels.

X-R-Site will host the XX-V model that contains the survey and topography. Modifications to the groundscape will need to be coordinated between the Landscape, Civil and Architectural scopes of work.
Link Worksets
There will also be a workset for each linked model, they should follow the nomenclature: X-R-[Name]. The first X is for External Reference, the second letter R is for Revit as these should be Revit models.

X-R-Architectural
X-R-Structural
X-R-Mechanical
X-R-Electrical
X-R-Plumbing
X-R-Fire Protection

Any major linked DWGs should follow the nomenclature: X-C-[Description]. The first X is for External Reference, the second letter C is CAD.

X-C-Survey
X-C-Existing Plans
X-C-Landscape
Workset Prefixes
To facilitate coordination and view control each discipline should use unique identifiers for each workset[s].

Each discipline should add the prefix to the workset that coincides with the Discipline Designator as defined in Sheet Naming.

Examples
Architecture	A-
A-Code Analysis
A-Entourage
A-Furniture
A-Interior
A-Shell and Core
Electrical	E-
Mechanical	M-
Plumbing	P-
Structure	S-

=== Background Views
Architectural backgrounds shall be derived from the following views within the Architectural model[s]:

	Floor Plans:
Floor Plan: LEVEL XX FLOOR PLAN

	Reflected Ceiling Plans:
Reflected Ceiling Plan: LEVEL XX REFLECTED CEILING PLAN

=== Graphics
All text should be Arial. General notes will be Arial 3/32”. BCJ will provide the project title block, view titles, and text styles for notes and schedules.

=== Sheet Format
The project sheet size will be Arch E1 (30” x 42”)

=== Sheet Naming
Sheet naming convention follows the format AA###x where the first two letters designate the discipline. The first number designates the Sheet. The second and third numbers are used for the sheet sequence.  Where necessary a letter suffix [a,b,c,..] will be used to designate enlarged plans.

AA###x
Discipline Designator

Designator	Discipline
G	General
H	Hazardous Materials
V	Survey/Mapping
B	Geotechnical
C	Civil
L	Landscape
S	Structural
A	Architectural
I	Interiors
Q	Equipment
F	Fire Protection
P	Plumbing
D	Process
M	Mechanical
E	Electrical
W	Distributed Energy
T	Telecommunications
R	Resource
X	Other Disciplines
Z	Contractor/Shop Drawings
O	Operations
	AA###x
Discipline Modifier

Modifier	Discipline
A	-	Architecture
	D	Demo
	S	Site
	P	Plinth
	G	Parking Garage Structure
	T	Office Tower



AA###x
Sheet Series

Designator	Sheet Type
0	General
1	Plans
2	Elevations
3	Sections
4	Enlarged Plans
5	Details
6	Vertical Circulation
7	Interior Elevations
8	Reflected Ceiling Plans
9	Schedules

	AA###x
Sequence

The last numbers are for sequencing the sheets. The sequence should match between sheet types where possible.

For example:
AT102a-Office Tower Second Floor Plan Area A
AP801a-Plinth First Floor RCP Area A

=== View Format
BCJ will provide view titles to consultants.

Views are arranged and numbered starting at the lower right side of the sheet and moving first to the top of the sheet then to the left. This ensures that drawings stay as far away from the bound edge as possible.

=== Shared Parameters
A shared parameters file will be provided by BCJ for transferring project specific parameters. Consultants should import the required shared parameters into their project at the direction of BCJ.  Shared parameters will be needed to schedule and any unique parameters on elements in more than one model.  The list below is provided to illustrate this setup.


Name	Description	Type	Example	Type/Inst	Categories
Schematic Design	SD Issuance	Text	12/31/2015	Type	Sheets
Design Development	DD Issuance	Text	12/31/2015	Type	Sheets
Construction Documents	CD Issuance	Text	12/31/2015	Type	Sheets
Addendum 01
Addendum Issuance
Text
12/31/2015
Type
Sheets

Sheet Group	To group sheets in sheet list	Integer	01	Type	Sheets

Door Type	Door type identifier	Text	F, DF, FG	Type	Doors
Door Material	Door material	Text	WD, HM	Type	Doors
Door Finish	Door finish	Text	WD1, P2	Inst	Doors
Frame Type	Frame type	Text	F1	Type	Doors, Windows
Frame Material	Frame material	Text	WD, HM	Type	Doors, Windows
Frame Finish	Frame finish	Text	WD1, P2	Inst	Doors, Windows
Jamb Detail	Jamb detail	Text	16/A5.03	Type	Doors, Windows
Head Detail	Head detail	Text	16/A5.03	Type	Doors, Windows
Sill Detail	Sill detail	Text	16/A5.03	Inst	Doors, Windows

=== Phasing
[CONFIRM – THIS MAY NEED TO INCLUDE MP PHASES AND SUB PHASES (I.E. PHASE 1A, 1B, 1C, ETC]
Description of phasing condition.

Existing			Description
New Construction		Description

=== Design Options
Design Options are an integral part of the design process, but should be eliminated from the model as soon as their study in the project has been complete. When used, the author of the Design Option should clearly name both the Option Set as well as the Options within the set so that they can be understood and toggled via Visibility Graphics efficiently.

The only Design Options that may remain in the design model indefinitely are those in which various arrangements are all equally likely to occur in the model; furniture layouts in an auditorium for instance. In these occurrences, it’s very important to clearly name the Option Set as well as the room or space to which the option set belongs.

=== Sheet Output
Sheet output from the BIM or other CAD software will be in .PDF format.  PDFs will orient sheets in landscape view.  Each sheet will be an individual .PDF file as to expedite creating a compiled PDF with bookmarks.  The file name for each sheet will follow the logic of sheet naming organization outlined in section File Naming :

[DisicplineDesignator][DisciplineModifier][SheetType#][Sequence#][enlargement suffix]-[SHEET-TITLE-CAPS-DASHES-NO-SPACES][YY_MMDDYYMMDD]
eg: AP801a-PL-FIRST-FLOOR-RCP-AREA-A_16_0123

ADD DATE IF REQUIRED – DISCUSS WITH TEAM


== Model Development
=== Description
 [If a separate contract exists, like AIA G202 it will take precedent over this section, make sure they are in concert with one another, or add one note to this section pointing to the contract]

=== Model Development Process
The following process is defined for the Record Model and the As-Built Model. Specific details to be confirmed by the project team:
•	BCJ and their consultants are responsible for the Design Intent Models. Contractor and their subcontractors are responsible for the As-Built Models.
•	BCJ will provide the coordinated Design Intent Record Models to Client at the conclusion of each major project phase. Client will then provide Contractor these models to be used for design coordination in collaboration with the Design Team and to be used as a reference for the creation of the initial Construction Model(s).
•	Contractor and their subcontractors will update the Construction Model with all as-built conditions and facility attribute data to form the As-Built Model deliverable back to Client.
•	See BIM Development Process Diagram for a diagram of the proposed workflow.

=== Level of Development
It is unfeasible to expect that all elements of the project will be modeled in detail in the Design Record Intent model. As a rudimentary rule of thumb, it should be expected that any elements that would traditionally be printed in a 1/8” = 1’-0” drawing would should up in the model at the appropriate time. Additional information regarding LOD and element geometry vs data can be found in the BIM Development Matrix.

Level of Development (LOD) is the level of completeness to which a model element is developed at the end of each project phase. Refer to the Model Development Plan & MEA for more details.

LOD 100:	Schematic Design; overall building massing; whole building analysis (volume, orientation, square footage costs)
LOD 200:	Design Development; generalized systems/assemblies (approximate quantities, size, shape, location, orientation); selected system performance analysis
LOD 300:	Construction Documentation; generation of traditional CD's; analysis and simulation of detailed elements/systems;
Coordinate with CM to determine what they will need from the level 300 model to help them facilitate subsequent models

=== Model Development Plan and Model Element Authors
This section is used to guide the project team in how to develop the model in order to achieve and accommodate the Model Uses and BIM Goals for the project defined in Model Use.

The Model development plan will be used to audit the BIM progress and coordinate the project team’s efforts throughout the project. This will be reviewed during the BIM Execution Review meetings described in Collaboration.

See appendix for the BIM Development Matrix for a full matrix of the Development Plan and MEA for the project. As this is a working document, these values and responsibilities will be refined throughout the project’s lifespan and will be discussed regularly.

=== Model Transfer for Contractor Use
It is BCJ’s policy that any BIM be transferred to the Contractor via the Owner. To that end, when a model is delivered for use by the Contractor, our policy also stipulates that we only deliver the geometry and associated data to that geometry. All other model elements are removed from the file. The preferred method of delivery is via an IFC4 file.

Additional information on model transfer for Owner and Contract use can be found in both the Right of Reliance section of this document as well as the Electronic File Designated Use License Agreement in the Appendix.

=== Facilities Management and Asset Attribute data
[It is assumed that UA will want a dataset of asset attributes at closeout for some type of integrated facilities management program. As of now, those final deliverables are unknown. This should be discussed at or before the BIM kickoff meeting to see what deliverables and/or standards should be anticipated during the Design phase as well as those anticipated from the Construction phase. For instances, some FM software will prepend an room name with the level it’s on but this data can only be an numeric value, therefore we’d have to name our levels differently for the FM data downstream.]

=== Model Closeout Deliverables
Team Members	Deliverable	Format
Design Team Project Closeout	Design Intent Record Model	.ifc format (Version 4)
	Record Document Digital Drawings	.pdf format
	Record Document Hard copy Drawings	3 sets

Contractor Project Closeout	Scanned Field Set Drawings – As-Builts	.tif format
	O&M Manuals	paper / .pdf / .xls format
	As-Built COBie Construction (worksheets 11, 14-28)	.xls format
	As Built FM / Coordination models	Their native format.


== Quality Control
=== Model Checking
Description
Types

Abbrev	Check Type	Definition
VC	Visual Check	Ensure there are no unintended model components and the design intent has been followed. Audit and purge models.
IC	Interference Check	Detect problems in the model where two building components are clashing
SC	Standards Check	Ensure that the BIM standard has been followed.
MI	Model Integrity Check	QC validation to ensure required meta-data, component categories and project compliant components are correct
Schedule

Check	Models	Responsible Parties	Software	Schedule
VC	A, M, E, P	Model Author(s)	Revit	Each major milestone at 50% and 100%.
SC	A, M, E, P	Model Author(s)	Revit
	This should be done continuously, but will be officially reviewed at the BIM Execution Meetings. See Meetings.

MI	A, M, E, P	Model Author(s)	Revit	100% DD, 90% CD
IC	A, S	Architecture	Revit
Navisworks	100%DD, 50% CD, 90% CD
IC	A, M	Architecture	Revit
Navisworks	100%DD, 50% CD, 90% CD
IC	S, M	Structure	Revit
Navisworks	100%DD, 50% CD, 90% CD
IC	S, P	Structure	Revit
Navisworks	100%DD, 50% CD, 90% CD
IC	S, M, P	Structure	Revit
Navisworks	100%DD, 50% CD, 90% CD


FP
P						MEP
E					MEP	MEP
M				MEP	MEP	MEP
S			S	S	S	S
A		A	A	A	A	A
	A	S	M	E	P	FP

The chart to the left identifies the IC checks to be completed during the project. Unless decided otherwise, official checks will take place in either Revit or Navisworks at: 100% DD, 50% CD, and 90% CD. A report will be exported from the software and distributed to the team as a record of the IC.

The party responsible for the IC check is shown at the intersection of the trades.

[appendix]
== External Documents
=== BIM Use Worksheet
=== Organizational Chart
=== BIM Development Process Diagram
=== BIM Development Matrix
=== COBie Workbook Template
=== Electronic File Designated Use License Agreement (original and returned)
=== Project Schedule including InfoExchanges
